### ISSUE TITLE
selfupdate broken

### ISSUE THREAD

**Issue by addshore** [addshore/dockerit#9]
Broken in v0.0.4 at least...

```
adam@adsh+wsl:~/dev/git/gerrit/mediawiki$ $ dockerit --selfupdate
panic: semver: Parse('v0.0.4'): Invalid character(s) found in major number "'v0"

goroutine 1 [running]:
github.com/blang/semver.MustParse(0x87784a0, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/blang/semver@v3.5.1+incompatible/semver.go:319 +0xf2
github.com/addshore/dockerit/cmd.glob..func1(0x8bb63c0, 0x9637008, 0x0, 0x1)
        /home/runner/work/dockerit/dockerit/cmd/root.go:54 +0x8e
github.com/spf13/cobra.(*Command).execute(0x8bb63c0, 0x940c058, 0x1, 0x1, 0x8bb63c0, 0x940c058)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x1e3
github.com/spf13/cobra.(*Command).ExecuteC(0x8bb63c0, 0x8bca802, 0x86a09ac, 0xa)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x291
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/addshore/dockerit/cmd.Execute(0x87784a0, 0x8, 0x8785600, 0x13)
        /home/runner/work/dockerit/dockerit/cmd/root.go:29 +0x184
main.main()
        /home/runner/work/dockerit/dockerit/main.go:15 +0x41
adam@adsh+wsl:~/dev/git/gerrit/mediawiki$ $ dockerit --version
Version: 'v0.0.4'
Built at : 2021-02-07T11:48:52
```

**Comment by addshore** [comment]
And in 0.0.5

```
panic: semver: Parse('v0.0.5'): Invalid character(s) found in major number "'v0"

goroutine 1 [running]:
github.com/blang/semver.MustParse(0x877e150, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/blang/semver@v3.5.1+incompatible/semver.go:319 +0x11e
github.com/addshore/dockerit/cmd.glob..func1(0x8bbe3c0, 0x9a0d008, 0x0, 0x1)
        /home/runner/work/dockerit/dockerit/cmd/root.go:54 +0x8e
github.com/spf13/cobra.(*Command).execute(0x8bbe3c0, 0x98a2018, 0x1, 0x1, 0x8bbe3c0, 0x98a2018)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x1e3
github.com/spf13/cobra.(*Command).ExecuteC(0x8bbe3c0, 0x8bd2822, 0x86a3a27, 0xa)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x291
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/addshore/dockerit/cmd.Execute(0x877e150, 0x8, 0x878b2d0, 0x13)
        /home/runner/work/dockerit/dockerit/cmd/root.go:29 +0x184
main.main()
        /home/runner/work/dockerit/dockerit/main.go:15 +0x41
```

**Comment by addshore** [comment]
```
$ $ dockerit --selfupdate
2021/02/20 10:53:22 Current binary is the latest version v0.0.6
```

:)
